### ISSUE TITLE
Kanban Board RoR Group Project

### ISSUE THREAD

**Issue by oovillagran** [oovillagran/recipe_app#17]
<h1>Hey there 👋</h1>

This is our kanban's board for our [Ruby on Rails group project](https://github.com/oovillagran/recipe_app/projects/1).

There are two members in our team.

Team member 1 - @oovillagran 
Team member 2 - @dazehinn 

<h2>Thanks for your kind review and feedback.</h2>

**Comment by souad988** [comment]
Hi @oovillagran  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved2](https://github.com/oovillagran/recipe_app/assets/59707859/cd14f6e1-4577-4666-8133-ef6a9ec6632d)


## Highlights
Tasks labeled with points
Destribute tasks equaly 
Add descriptive titles

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
